
package com.jakubstas.ignis.wemo.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BasicServicePortType", targetNamespace = "")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BasicServicePortType {


    /**
     * 
     * @param setBinaryStateInputPart
     * @return
     *     returns com.jakubstas.ignis.wemo.wsdl.SetBinaryStateResponse
     */
    @WebMethod(operationName = "SetBinaryState", action = "urn:Belkin:service:basicevent:1#SetBinaryState")
    @WebResult(name = "SetBinaryStateResponse", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "SetBinaryStateOutputPart")
    public SetBinaryStateResponse setBinaryState(
        @WebParam(name = "SetBinaryState", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "SetBinaryStateInputPart")
        SetBinaryState setBinaryStateInputPart);

    /**
     * 
     * @param getBinaryStateInputPart
     * @return
     *     returns com.jakubstas.ignis.wemo.wsdl.GetBinaryStateResponse
     */
    @WebMethod(operationName = "GetBinaryState", action = "urn:Belkin:service:basicevent:1#GetBinaryState")
    @WebResult(name = "GetBinaryStateResponse", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "GetBinaryStateOutputPart")
    public GetBinaryStateResponse getBinaryState(
        @WebParam(name = "GetBinaryState", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "GetBinaryStateInputPart")
        GetBinaryState getBinaryStateInputPart);

    /**
     * 
     * @param getFriendlyNameInputPart
     * @return
     *     returns com.jakubstas.ignis.wemo.wsdl.GetFriendlyNameResponse
     */
    @WebMethod(operationName = "GetFriendlyName", action = "urn:Belkin:service:basicevent:1#GetFriendlyName")
    @WebResult(name = "GetFriendlyNameResponse", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "GetFriendlyNameOutputPart")
    public GetFriendlyNameResponse getFriendlyName(
        @WebParam(name = "GetFriendlyName", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "GetFriendlyNameInputPart")
        GetFriendlyName getFriendlyNameInputPart);

    /**
     * 
     * @param getHomeIdInputPart
     * @return
     *     returns com.jakubstas.ignis.wemo.wsdl.GetHomeIdResponse
     */
    @WebMethod(operationName = "GetHomeId", action = "urn:Belkin:service:basicevent:1#GetHomeId")
    @WebResult(name = "GetHomeIdResponse", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "GetHomeIdOutputPart")
    public GetHomeIdResponse getHomeId(
        @WebParam(name = "GetHomeId", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "GetHomeIdInputPart")
        GetHomeId getHomeIdInputPart);

    /**
     * 
     * @param getSignalStrengthInputPart
     * @return
     *     returns com.jakubstas.ignis.wemo.wsdl.GetSignalStrengthResponse
     */
    @WebMethod(operationName = "GetSignalStrength", action = "urn:Belkin:service:basicevent:1#GetSignalStrength")
    @WebResult(name = "GetSignalStrengthResponse", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "GetSignalStrengthOutputPart")
    public GetSignalStrengthResponse getSignalStrength(
        @WebParam(name = "GetSignalStrength", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "GetSignalStrengthInputPart")
        GetSignalStrength getSignalStrengthInputPart);

    /**
     * 
     * @param getLogFileURLInputPart
     * @return
     *     returns com.jakubstas.ignis.wemo.wsdl.GetLogFileURLResponse
     */
    @WebMethod(operationName = "GetLogFileURL", action = "urn:Belkin:service:basicevent:1#GetLogFileURL")
    @WebResult(name = "GetLogFileURLResponse", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "GetLogFileURLOutputPart")
    public GetLogFileURLResponse getLogFileURL(
        @WebParam(name = "GetLogFileURL", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "GetLogFileURLInputPart")
        GetLogFileURL getLogFileURLInputPart);

    /**
     * 
     * @param getIconURLInputPart
     * @return
     *     returns com.jakubstas.ignis.wemo.wsdl.GetIconURLResponse
     */
    @WebMethod(operationName = "GetIconURL", action = "urn:Belkin:service:basicevent:1#GetIconURL")
    @WebResult(name = "GetIconURLResponse", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "GetIconURLOutputPart")
    public GetIconURLResponse getIconURL(
        @WebParam(name = "GetIconURL", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "GetIconURLInputPart")
        GetIconURL getIconURLInputPart);

    /**
     * 
     * @param changeFriendlyNameInputPart
     * @return
     *     returns com.jakubstas.ignis.wemo.wsdl.ChangeFriendlyNameResponse
     */
    @WebMethod(operationName = "ChangeFriendlyName", action = "urn:Belkin:service:basicevent:1#ChangeFriendlyName")
    @WebResult(name = "ChangeFriendlyNameResponse", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "ChangeFriendlyNameOutputPart")
    public ChangeFriendlyNameResponse changeFriendlyName(
        @WebParam(name = "ChangeFriendlyName", targetNamespace = "urn:Belkin:service:basicevent:1", partName = "ChangeFriendlyNameInputPart")
        ChangeFriendlyName changeFriendlyNameInputPart);

}
